# Generated by Django 3.2.12 on 2022-09-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
