# Generated by Django 3.2.12 on 2022-10-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20221007_1805'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendship',
            name='unique_friendship',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
