# Generated by Django 3.2.12 on 2022-11-10 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20221007_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='followed',
            new_name='follower',
        ),
    ]
